# Generated by Django 3.0.8 on 2022-01-14 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CUSTOMERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_name', models.CharField(max_length=20)),
                ('Ph_no', models.IntegerField()),
                ('Address', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_Descript', models.CharField(max_length=30)),
                ('Price', models.FloatField()),
                ('hlink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ORDERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ordered_by', models.CharField(max_length=20)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparel.CUSTOMERS')),
                ('P_id', models.ManyToManyField(to='apparel.PRODUCTS')),
            ],
        ),
    ]
